version: '3'
services:

  cqcmp-mysql6:
    image: "mysql:latest"
    container_name: cqcmp-mysql6
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init-script.sql
      - mysql-data:/var/lib/mysql6/data2
    ports:
      - 3308:3306
    environment:
      - MYSQL_DB:CQCMP
      - MYSQL_USER:cqcmp_user
      - MYSQL_PASSWORD:cqcmp_password
      - MYSQL_ROOT_PASSWORD=password

  cqcmp-app8:
    image: "priyanko27/cqcmp:latest"
    container_name: cqcmp-app8
    environment:
      - DB_SERVER=cqcmp-mysql6
    ports:
      - 8102:8095
    links:
      - cqcmp-mysql6

  cqcmp-ui:
    image: "priyanko27/cqcmp_fe:latest"
    container_name: cqcmp-ui
    ports:
      - 4200:3000
    links:
      - cqcmp-app8


volumes:
  mysql-data:
